
export const types={
    FILL_POSTS:        'FILL_POSTS',
    CREATE_POST:       'CREATE_POST',
    REMOVE_POST:       'REMOVE_POST',
    CLEAR_POSTS:       'CLEAR_POSTS',
    FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
};
