export const types={
    FILL_PROFILE:        'FILL_PROFILE',
    UPDATE_AVATAR:       'UPDATE_AVATAR',
    CLEAR_PROFILE:       'CLEAR_PROFILE',
    SIGNUP_ASYNC:        'SIGNUP_ASYNC',
    UPDATE_NAME_ASYNC:   ' UPDATE_NAME_ASYNC',
    UPDATE_AVATAR_ASYNC: 'UPDATE_AVATAR_ASYNC',
};
